# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: My Portfolio
site_url: https://lsharma-202.github.io
theme:
  name: material
  palette:

  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: brown
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode
